# Generated by Django 5.2.8 on 2025-11-07 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.JSONField()),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
